
analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: ignore
    library_private_types_in_public_api: ignore
    override_on_non_overriding_member: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:

