name: walchain
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Light.otf
        - asset: assets/fonts/GeneralSans-Semibold.otf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

# flutter_native_splash:

#   color: "#6255a4"
#   image: assets/images/logo.png

#   android_12:
#     color: "#6255a4"
#     image: assets/images/androidLogo.png

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/launcher_icon.png"
#   min_sdk_android: 21 
#   web:
#     generate: true
#     image_path: "assets/images/launcher_icon.png"
#     background_color: "#hexcode"
#     theme_color: "#6255a4"
  





